### ISSUE TITLE
App crashes on iOS14 and earlier while loading dlyb

### ISSUE THREAD

**Issue by dchudov** [Swiftgram/TDLibKit#27]
Application crashes on iOS 13 and iOS 14 while loading dlyb. Works fine on iOS 15 and iOS 16.

Crashes on release versions **_1.2.1-tdlib-1.8.4-b393215d_** till current(**_1.2.1-tdlib-1.8.10-758ced94_**)
Works fine on version **_1.2.1-tdlib-1.8.3-047246f3_** and earlier.

Reproduced on iPhone 12 (iOS14.8.1) and Xcode Simulators.

**Console log:**
```
dyld: Symbol not found: __ZTTNSt3__118basic_stringstreamIcNS_11char_traitsIcEENS_9allocatorIcEEEE
  Referenced from: /Users/dchudov/Library/Developer/CoreSimulator/Devices/504B2D45-08FD-4EA7-B470-8D6BCE489A84/data/Containers/Bundle/Application/6C0069DF-A3F2-4766-94A9-989087020EAB/testApp.app/testApp
  Expected in: /usr/lib/libc++.1.dylib
 in /Users/dchudov/Library/Developer/CoreSimulator/Devices/504B2D45-08FD-4EA7-B470-8D6BCE489A84/data/Containers/Bundle/Application/6C0069DF-A3F2-4766-94A9-989087020EAB/testApp.app/testApp
dyld: launch, loading dependent libraries
DYLD_SHARED_CACHE_DIR=/Users/dchudov/Library/Developer/CoreSimulator/Caches/dyld/22D49/com.apple.CoreSimulator.SimRuntime.iOS-14-5.18E182
DYLD_ROOT_PATH=/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 14.5.simruntime/Contents/Resources/RuntimeRoot
DYLD_LIBRARY_PATH=/Users/dchudov/Library/Developer/Xcode/DerivedData/unions-bqegwvjilltzcbdhyezbhavihriw/Build/Products/Debug-iphonesimulator:/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 14.5.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 14.5.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libBacktraceRecording.dylib:/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 14.5.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libMainThreadChecker.dylib:/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 14.5.simruntime/Contents/Resources/RuntimeRoot/Developer/Library/PrivateFrameworks/DTDDISupport.frame
```

**Thread stack:**
```
Thread 1#0	0x000000011f3a7b4a in __abort_with_payload ()
#1	0x000000011f3c0d07 in abort_with_payload_wrapper_internal ()
#2	0x000000011f3c0d39 in abort_with_payload ()
#3	0x0000000112cafef8 in abort_with_payload ()
#4	0x0000000112c666bf in dyld::halt(char const*) ()
#5	0x0000000112c691a5 in dyld::_main(macho_header const*, unsigned long, int, char const**, char const**, char const**, unsigned long*) ()
#6	0x0000000112c631c2 in start_sim ()
#7	0x000000011f345ff1 in dyld4::prepareSim(dyld4::RuntimeState&, char const*) ()
#8	0x000000011f3445be in dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) ()
#9	0x000000011f344281 in start ()
```

**Runtime:**
```
dyld`:
    0x11f3a7b40 <+0>:  movl   $0x2000209, %eax          ; imm = 0x2000209 
    0x11f3a7b45 <+5>:  movq   %rcx, %r10
    0x11f3a7b48 <+8>:  syscall 
->  0x11f3a7b4a <+10>: jae    0x11f3a7b54               ; <+20>
    0x11f3a7b4c <+12>: movq   %rax, %rdi
    0x11f3a7b4f <+15>: jmp    0x11f341178               ; cerror_nocancel
    0x11f3a7b54 <+20>: retq   
    0x11f3a7b55 <+21>: nop    
    0x11f3a7b56 <+22>: nop    
    0x11f3a7b57 <+23>: nop    
```

**Comment by Kylmakalle** [comment]
@dchudov This should be solved in the latest TDLibKit versions (incoming in an hour). Minimum supported iOS version is 11.
